### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by hhiep1504** [jixunbo/LightMBN#31]
I have set the dataset CUHK03 as in ReIDataset folder but this issue occured
![image](https://github.com/user-attachments/assets/f6d53718-7d6a-496b-baa9-94b3fb44575f)

Experiment results will be saved in C:\Users\ADMIN\Documents\LightMBN_hiep/experiment/test 
Building train transforms ...
+ resize to 384x128
+ random flip
+ random crop (enlarge to 403x134 and crop 384x128)
+ to torch tensor of range [0, 1]
+ normalization (mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
+ random erase
Building test transforms ...
+ resize to 384x128
+ to torch tensor of range [0, 1]
+ normalization (mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
=> Loading train (source) dataset
=> Loading test (target) dataset

  **************** Summary ****************
  train            : ['cuhk03_splited']
   train datasets : 1
   train ids      : 767
   train images   : 7365
   train cameras  : 2
  test             : ['cuhk03_splited']
   query images   : 1400
   gallery images : 5332
  *****************************************

[INFO] Building LMBN_n model... Time used: 0 m 0 s
Successfully loaded imagenet pretrained weights from "C:\Users\ADMIN/.cache\torch\checkpoints\osnet_x1_0_imagenet.pth"
C:\Users\ADMIN\Documents\LightMBN_hiep\utils\utility.py:203: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See 
https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any 
use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(fpath, map_location=map_location)
[INFO] Successfully loaded pretrained weights from "lmbn_n_cuhk03_d.pth" Time used: 0 m 2 s
[INFO] Model parameters: 9406112 flops: 2430894432 Time used: 0 m 4 s
[INFO] GPU: NVIDIA GeForce 940MX Time used: 0 m 4 s
[INFO] Starting from epoch 1 Time used: 0 m 4 s

[INFO] Test: Time used: 0 m 4 s
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\ADMIN\anaconda3\envs\reid\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\ADMIN\anaconda3\envs\reid\lib\site-packages\prefetch_generator\__init__.py", line 80, in run
    for item in self.generator:
  File "C:\Users\ADMIN\anaconda3\envs\reid\lib\site-packages\torch\utils\data\dataloader.py", line 630, in __next__
    data = self._next_data()
  File "C:\Users\ADMIN\anaconda3\envs\reid\lib\site-packages\torch\utils\data\dataloader.py", line 1344, in _next_data
    return self._process_data(data)
  File "C:\Users\ADMIN\anaconda3\envs\reid\lib\site-packages\torch\utils\data\dataloader.py", line 1370, in _process_data
    data.reraise()
  File "C:\Users\ADMIN\anaconda3\envs\reid\lib\site-packages\torch\_utils.py", line 706, in reraise
    raise exception
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\ADMIN\anaconda3\envs\reid\lib\site-packages\torch\utils\data\_utils\worker.py", line 309, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "C:\Users\ADMIN\anaconda3\envs\reid\lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\ADMIN\anaconda3\envs\reid\lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\ADMIN\Documents\LightMBN_hiep\data_v2\datasets\dataset.py", line 246, in __getitem__
    img = read_image(img_path)
  File "C:\Users\ADMIN\Documents\LightMBN_hiep\data_v2\utils.py", line 109, in read_image
    raise IOError('"{}" does not exist'.format(path))
OSError: "C:\Users\ADMIN\Documents\LightMBN_hiep\ReIDataset\CUHK03\_003_1_02.png" does not exist

**Comment by fubel** [comment]
Hey, this might be due to our code expecting UNIX-like paths. You could try to adjust this in the code or build the code within a Ubuntu Docker.
